title: ReactomeGSA - Comparative multi-omics pathway analyses
description: The ReactomeGSA project supports multi-omics, comparative pathway analyses using the Reactome pathway database.
sitename: ReactomeGSA
baseurl: '/ReactomeGSA'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME